version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - apps/backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - mindfactory_challenge_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -h localhost -p $POSTGRES_PORT"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  backend:
    build:
      context: ./apps/backend/
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - apps/backend/.env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - mindfactory_challenge_network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./apps/frontend/
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - mindfactory_challenge_network 
    restart: unless-stopped

networks:
  mindfactory_challenge_network:
    driver: bridge

volumes:
  postgres_data:
